%% ============================================================
%  北斗 B1I 抗干扰仿真系统
%  Beidou B1I Anti-Jamming Simulation System
%
%  功能说明：
%    模拟北斗 B1I 卫星信号，构建三种典型干扰环境
%    （窄带连续波、宽带噪声、脉冲干扰），实现三种
%    对应抗干扰算法，并进行量化性能评估。
%
%  运行方法：MATLAB 中直接 F5 运行
%  依赖工具箱：Signal Processing Toolbox
%
%  适合人群：
%    - 北斗导航芯片/算法岗位面试作品
%    - GNSS 抗干扰技术学习者
%    - 卫星定位系统仿真入门
%
%  Version 1.0  |  2026-07
% ============================================================

clear; close all; clc;
rng(42);  % 固定随机种子，确保每次运行结果可复现
          % Fix random seed for reproducible results

fprintf('\n');
fprintf('╔══════════════════════════════════════════════╗\n');
fprintf('║    北斗 B1I 抗干扰仿真系统                    ║\n');
fprintf('║    Beidou B1I Anti-Jamming Simulation        ║\n');
fprintf('╚══════════════════════════════════════════════╝\n\n');

%% ============================================================
%  第 1 部分：系统参数配置
%  Part 1: System Parameter Configuration
%
%  ★ 所有可调参数集中在这里，方便快速修改场景
%  All tunable parameters are centralized here
% ============================================================
fprintf('▶ [1/6] 系统参数配置\n');

% ── 北斗 B1I 信号真实参数 ──
%  Beidou B1I is the open-service signal on B1 band (1561.098 MHz)
%  We simulate at a lower intermediate frequency (IF) after downconversion
IF          = 4.098e6;      % 中频 Intermediate Frequency      [Hz]
                             % 真实载波 1561.098 MHz → 下变频到 4.098 MHz
code_rate   = 2.046e6;      % 码速率 Code rate  [chip/s]
code_len    = 2046;          % PRN 码长度 Code length [chips]
code_period = 1e-3;          % 码周期 Code period = 2046/2.046e6 [s]
data_rate   = 50;            % 导航电文速率 Data rate [bps]

% ── 仿真采样参数 ──
Fs = 20.46e6;                % 采样率 Sampling rate  [Hz]
                              % 20.46 MHz = 10 × code_rate
                              % 满足奈奎斯特定理（> 2 × IF = 8.196 MHz）
Ts = 1/Fs;                   % 采样间隔 Sampling interval [s]
sim_ms = 2;                  % 仿真时长 Simulation length [ms]
sim_time = sim_ms * 1e-3;    % 转秒 [s]
n_samples = round(Fs * sim_time);  % 总采样点数

% ── 干扰参数 Jamming Parameters ──
%  干信比 JSR = 10*log10(P_jammer / P_signal)
JSR_CW_dB   = 30;    % 窄带连续波干扰 (CW) 干信比 [dB]
JSR_WB_dB   = 25;    % 宽带噪声干扰 (Wideband) 干信比 [dB]
JSR_Pulse_dB = 35;   % 脉冲干扰 (Pulse) 干信比 [dB]

%  窄带干扰：频率偏置
jam_freq_offset = 0.3e6;     % 干扰频率 = IF + jam_freq_offset [Hz]

%  宽带干扰：噪声带宽
wb_bw = 4e6;                 % 宽带噪声带宽 [Hz] (约 2× 码速率)

%  脉冲干扰：周期性高功率短脉冲
pulse_duty = 0.05;           % 占空比 Duty cycle (5%)
pulse_period = 0.5e-3;       % 脉冲周期 Pulse period [s]

% ── 抗干扰算法参数 ──
%  Adaptive Notch Filter
mu_notch = 0.01;             % LMS 步长 (控制收敛速度与稳态误差)

%  Frequency Domain Excision
excise_factor = 3.0;         % 阈值因子 = mean + excise_factor × std

%  Pulse Blanking
blank_factor  = 4.0;         % 脉冲检测阈值因子
smooth_win    = 5;           % 平滑窗长度

fprintf('  ✅ 采样率 Fs = %.2f MHz\n', Fs/1e6);
fprintf('  ✅ 中频 IF  = %.3f MHz  (真实载波 1561.098 MHz 下变频)\n', IF/1e6);
fprintf('  ✅ 码速率    = %.3f Mcps  |  码长 %d chips  |  周期 %d ms\n', ...
        code_rate/1e6, code_len, round(code_period*1e3));
fprintf('  ✅ 仿真时长  = %d ms  (%d 采样点)\n', sim_ms, n_samples);
fprintf('  ✅ 干信比    |  CW: %ddB  |  宽带: %ddB  |  脉冲: %ddB\n\n', ...
        JSR_CW_dB, JSR_WB_dB, JSR_Pulse_dB);


%% ============================================================
%  第 2 部分：北斗 B1I 信号生成
%  Part 2: Beidou B1I Signal Generation
%
%  流程：PRN 码生成 → BPSK 调制 → 功率归一化
% ============================================================
fprintf('▶ [2/6] 北斗 B1I 信号生成\n');

% ── 2.1 生成 PRN 码 ──
%  B1I 使用 2046 位 Gold 码，这里用 m 序列近似
%  m-sequence generated by LFSR with primitive polynomial x^11 + x^2 + 1
%  This produces a 2^11 - 1 = 2047 chip sequence, truncated to 2046
n_stages = 11;
lfsr = ones(1, n_stages);     % LFSR 初始状态全 1
mseq_len = 2^n_stages - 1;    % 2047
mseq = zeros(1, mseq_len);

for i = 1:mseq_len
    mseq(i) = lfsr(end);      % 输出最后一级
    % 反馈多项式: x^11 + x^2 + 1 → 取第 11 级和第 2 级异或
    fb = xor(lfsr(end), lfsr(2));
    lfsr = [fb, lfsr(1:end-1)];  % 右移
end

% 转为 ±1 序列并截取 2046 位（B1I 标准长度）
prn_chips = 2 * (mseq(1:code_len) > 0.5) - 1;

% ── 2.2 上采样到采样率 ──
%  PRN 码是码片序列，每个码片持续 Tc = 1/code_rate
%  需要将序列映射到采样时间轴上
samples_per_chip = Fs / code_rate;  % 每码片采样点数 ≈ 10

% 生成完整的时间轴
t = (0:n_samples-1) * Ts;

% 将码片序列重复至覆盖仿真的 2 个码周期
num_periods = ceil(sim_time / code_period);
code_seq = repmat(prn_chips, 1, num_periods);

% 码片级时间轴（0 ~ num_periods*code_len 个码片）
chip_time = (0:num_periods*code_len-1) / code_rate;

% 将码片序列插值到采样时间轴
code_signal = interp1(chip_time, code_seq, t, 'nearest');
% 使用 'nearest' 保持方波形（BPSK 是硬切换）

% ── 2.3 BPSK 调制到中频 ──
%  B1I 采用 QPSK 调制，我们简化为 BPSK（原理相同）
%  s(t) = A · d(t) · c(t) · cos(2π·f_IF·t)
%  其中 d(t) 是导航电文（本仿真设 d(t)=1，即导频信号）
carrier = cos(2*pi*IF * t);
signal_clean = code_signal .* carrier;  % BPSK 调制

% ── 2.4 信号功率归一化 ──
%  计算信号功率，方便后续按 JSR 添加干扰
signal_power = mean(signal_clean.^2);
fprintf('  ✅ PRN 码生成完成  (2046 chips, m-sequence)\n');
fprintf('  ✅ BPSK 调制完成  (IF = %.3f MHz)\n', IF/1e6);
fprintf('  ✅ 信号功率 = %.2e  (归一化基准)\n\n', signal_power);

% ── 图 1：B1I 信号时域与频域特性 ──
figure('Name', '北斗 B1I 信号特性', 'Position', [100, 100, 1200, 500]);

subplot(2,3,1);
stem(prn_chips(1:50), 'b-', 'MarkerFaceColor', 'b', 'MarkerSize', 3);
title('① PRN 码前 50 chips');
xlabel('Chip index'); ylabel('幅度');
ylim([-1.5, 1.5]); grid on;

subplot(2,3,2);
% 画时域信号前 500 点（看清楚 BPSK 相位跳变）
plot(t(1:500)*1e6, signal_clean(1:500), 'b-', 'LineWidth', 1.0);
title('② B1I 信号时域波形 (前 500 采样点)');
xlabel('时间 (μs)'); ylabel('幅度');
grid on;

subplot(2,3,3);
% FFT 频谱
N_fft = 2^nextpow2(n_samples);
X_clean = fft(signal_clean, N_fft);
f_axis = (-N_fft/2:N_fft/2-1) * Fs / N_fft;
X_clean_shift = fftshift(X_clean);
plot(f_axis/1e6, abs(X_clean_shift)/N_fft, 'b-', 'LineWidth', 1.2);
title('③ 频谱 (中频 4.098 MHz)');
xlabel('频率 (MHz)'); ylabel('幅度');
xlim([-2, 10]); grid on;
xline(IF/1e6, 'r--', 'IF=4.098MHz', 'LabelOrientation', 'horizontal');
xline(-IF/1e6, 'r--', 'LabelOrientation', 'horizontal');

subplot(2,3,4);
% PRN 码自相关
[autocorr, lags] = xcorr(prn_chips, prn_chips, 'normalized');
plot(lags, autocorr, 'b-', 'LineWidth', 1.5);
title('④ PRN 码自相关特性');
xlabel('偏移 (chips)'); ylabel('相关值');
xlim([-100, 100]); grid on;

subplot(2,3,5);
% 循环谱密度（中频附近放大）
zoom_range = f_axis >= IF - 2e6 & f_axis <= IF + 2e6;
f_zoom = f_axis(zoom_range);
spec_zoom = abs(X_clean_shift(zoom_range))/N_fft;
plot(f_zoom/1e6, spec_zoom, 'b-', 'LineWidth', 1.5);
title('⑤ 中频附近频谱细节');
xlabel('频率 (MHz)'); ylabel('幅度');
grid on;
xline(IF/1e6, 'r--', 'IF', 'LabelOrientation', 'horizontal');

subplot(2,3,6);
% 星座图（I/Q 分量）
sig_hilbert = hilbert(signal_clean);
plot(real(sig_hilbert(1:2000)), imag(sig_hilbert(1:2000)), 'b.', 'MarkerSize', 2);
title('⑥ BPSK 星座图 (I/Q)');
xlabel('同相 I'); ylabel('正交 Q');
axis equal; grid on;
xlim([-1.5, 1.5]); ylim([-1.5, 1.5]);

% 兼容旧版 MATLAB（R2018a 以下无 sgtitle）
if ~verLessThan('matlab', '9.4')  % R2018a = 9.4
    sgtitle('北斗 B1I 信号特性分析 (Beidou B1I Signal Characteristics)', ...
             'FontSize', 13, 'FontWeight', 'bold');
else
    suptitle('北斗 B1I 信号特性分析 (Beidou B1I Signal Characteristics)');
end


%% ============================================================
%  第 3 部分：三种干扰信号模型
%  Part 3: Interference Signal Models
%
%  模拟三种典型压制式干扰：
%    (a) 窄带连续波 CW — 瞄准式干扰，能量集中
%    (b) 宽带噪声 — 阻塞式干扰，覆盖整个频带
%    (c) 脉冲干扰 — 周期性大功率短脉冲
% ============================================================
fprintf('▶ [3/6] 干扰信号生成\n');

% ── 3.1 窄带连续波干扰 (CW) ──
%  模拟敌方瞄准式干扰机，频率对准北斗信号频段
jam_freq_cw = IF + jam_freq_offset;  % 干扰频率
jam_amp_cw = sqrt(10^(JSR_CW_dB/10) * signal_power * 2);
   % 幅度计算：JSR(dB) = 10*log10(P_jam/P_sig)
   % 对于正弦波 sin(2πft)，功率 = A²/2
   % 所以 A = sqrt(2 * P_jam) = sqrt(2 * P_sig * 10^(JSR/10))
jam_cw = jam_amp_cw * sin(2*pi*jam_freq_cw * t);

% ── 3.2 宽带噪声干扰 ──
%  模拟阻塞式干扰，用带限高斯白噪声
%  带宽覆盖信号主瓣（约 2× 码速率 = 4.092 MHz）
noise_white = randn(1, n_samples);  % 高斯白噪声
% 用 FIR 带通滤波器限带
[b_wb, a_wb] = butter(4, ...
    [IF - wb_bw/2, IF + wb_bw/2] / (Fs/2), 'bandpass');
jam_wideband_raw = filter(b_wb, a_wb, noise_white);
jam_wideband_raw = jam_wideband_raw / sqrt(mean(jam_wideband_raw.^2));
   % 功率归一化
jam_amp_wb = sqrt(10^(JSR_WB_dB/10) * signal_power);
jam_wideband = jam_amp_wb * jam_wideband_raw;

% ── 3.3 脉冲干扰 ──
%  模拟周期性高功率脉冲，在短时间内释放极大能量
%  用来压制接收机前端，使其饱和
pulse_on_samples = round(pulse_duty * pulse_period / Ts);       % 脉冲持续采样数
pulse_off_samples = round((1 - pulse_duty) * pulse_period / Ts); % 间隔采样数
pulse_one_period = [ones(1, pulse_on_samples), zeros(1, pulse_off_samples)];
pulse_train = repmat(pulse_one_period, 1, ...
    ceil(n_samples / length(pulse_one_period)));
pulse_train = pulse_train(1:n_samples);  % 截断到仿真长度

jam_amp_pulse = sqrt(10^(JSR_Pulse_dB/10) * signal_power);
jam_pulse = jam_amp_pulse * pulse_train .* randn(1, n_samples);
   % 脉冲内填充白噪声（模拟噪声脉冲）

fprintf('  ✅ CW 干扰    |  频率 %.3f MHz  |  JSR = %d dB\n', ...
        jam_freq_cw/1e6, JSR_CW_dB);
fprintf('  ✅ 宽带干扰   |  带宽 %d MHz (中频附近)  |  JSR = %d dB\n', ...
        wb_bw/1e6, JSR_WB_dB);
fprintf('  ✅ 脉冲干扰   |  占空比 %.0f%%  |  周期 %.1f ms  |  JSR = %d dB\n\n', ...
        pulse_duty*100, pulse_period*1e3, JSR_Pulse_dB);

% ── 图 2：三种干扰信号的时域和频域特性 ──
figure('Name', '三种干扰信号特性', 'Position', [100, 100, 1200, 700]);

% 时域波形（3 行）
plot_idx = 1;
for jammer = {'CW', 'Wideband', 'Pulse'}
    jam_signal = eval(['jam_' lower(jammer{1})]);
    
    subplot(3, 2, plot_idx);
    plot(t(1:2000)*1e6, jam_signal(1:2000), 'r-', 'LineWidth', 0.8);
    title(sprintf('(%s) 时域波形', jammer{1}));
    xlabel('时间 (μs)'); ylabel('幅度');
    grid on;
    
    subplot(3, 2, plot_idx+1);
    X_jam = fftshift(fft(jam_signal, N_fft));
    plot(f_axis/1e6, abs(X_jam)/N_fft, 'r-', 'LineWidth', 1.0);
    title(sprintf('(%s) 频谱', jammer{1}));
    xlabel('频率 (MHz)'); ylabel('幅度');
    xlim([-2, 10]); grid on;
    
    plot_idx = plot_idx + 2;
end

if ~verLessThan('matlab', '9.4')
    sgtitle('三种压制式干扰信号 (Three Types of Jamming Signals)', ...
            'FontSize', 13, 'FontWeight', 'bold');
else
    suptitle('三种压制式干扰信号 (Three Types of Jamming Signals)');
end


%% ============================================================
%  第 4 部分：干扰对信号捕获的影响
%  Part 4: Impact of Jamming on Signal Acquisition
%
%  卫星导航接收机通过 PRN 码相关来捕获卫星
%  干扰会降低相关峰信噪比，严重时导致捕获失败
%  相关峰衰减量 = 20*log10(峰值_干扰 / 峰值_干净)
% ============================================================
fprintf('▶ [4/6] 干扰对捕获性能的影响分析\n');

% ── 构建三种含干扰信号 ──
rx_cw    = signal_clean + jam_cw;         % 含窄带干扰
rx_wb    = signal_clean + jam_wideband;   % 含宽带干扰
rx_pulse = signal_clean + jam_pulse;      % 含脉冲干扰

% ── 本地 PRN 码参考 (用于相关) ──
%  接收机本地生成相同的 PRN 码，上采样到采样率
%  ★ 注意：必须也乘上同频载波，因为 signal_clean 是 BPSK 调制信号
%    如果直接用 baseband 码和 BPSK 信号做相关，结果≈0（载波平均掉了）
%    这就是之前 Figure 3 空白的根本原因！
local_code = interp1(chip_time, code_seq, t, 'nearest');
local_ref  = local_code .* carrier;  % 本地参考 = PRN码 × 同频载波

% ── 计算相关峰 ──
%  用 xcorr 计算接收信号与本地码的相关
%  归一化到 [0,1] 范围方便对比
[corr_clean, lags] = xcorr(signal_clean, local_ref, 'normalized');
corr_cw    = xcorr(rx_cw,    local_ref, 'normalized');
corr_wb    = xcorr(rx_wb,    local_ref, 'normalized');
corr_pulse = xcorr(rx_pulse, local_ref, 'normalized');

lags_us = lags / Fs * 1e6;  % 转为微秒

% ── 提取峰值 ──
peak_clean = max(abs(corr_clean));
peak_cw    = max(abs(corr_cw));
peak_wb    = max(abs(corr_wb));
peak_pulse = max(abs(corr_pulse));

% 计算衰减 (dB)
atten_cw    = 20*log10(peak_cw / peak_clean);
atten_wb    = 20*log10(peak_wb / peak_clean);
atten_pulse = 20*log10(peak_pulse / peak_clean);

fprintf('  📊 相关峰衰减 (负值表示相关峰降低):\n');
fprintf('     - 干净信号:  峰值 = %.4f  (基准)\n', peak_clean);
fprintf('     - +CW 干扰:  峰值 = %.4f  |  衰减 %.1f dB\n', peak_cw, atten_cw);
fprintf('     - +宽带干扰: 峰值 = %.4f  |  衰减 %.1f dB\n', peak_wb, atten_wb);
fprintf('     - +脉冲干扰: 峰值 = %.4f  |  衰减 %.1f dB\n\n', peak_pulse, atten_pulse);

% ── 图 3：四种场景的相关峰对比 ──
figure('Name', '干扰对相关峰的影响', 'Position', [100, 100, 1000, 700]);

% 先画干净信号的相关峰（基准）
subplot(2,2,1);
plot(lags_us, abs(corr_clean), 'b-', 'LineWidth', 1.5);
title(sprintf('① 干净信号 (基准)  峰值 = %.3f', peak_clean));
xlabel('时延 (μs)'); ylabel('归一化相关值');
xlim([-20, 20]); grid on;

subplot(2,2,2);
plot(lags_us, abs(corr_cw), 'r-', 'LineWidth', 1.5);
title(sprintf('② + CW 窄带干扰  衰减 %.1f dB', atten_cw));
xlabel('时延 (μs)'); ylabel('归一化相关值');
xlim([-20, 20]); grid on;

subplot(2,2,3);
plot(lags_us, abs(corr_wb), 'r-', 'LineWidth', 1.5);
title(sprintf('③ + 宽带噪声干扰  衰减 %.1f dB', atten_wb));
xlabel('时延 (μs)'); ylabel('归一化相关值');
xlim([-20, 20]); grid on;

subplot(2,2,4);
plot(lags_us, abs(corr_pulse), 'r-', 'LineWidth', 1.5);
title(sprintf('④ + 脉冲干扰  衰减 %.1f dB', atten_pulse));
xlabel('时延 (μs)'); ylabel('归一化相关值');
xlim([-20, 20]); grid on;

if ~verLessThan('matlab', '9.4')
    sgtitle('干扰对 PRN 码相关峰的影响 (Impact of Jamming on Correlation Peak)', ...
            'FontSize', 13, 'FontWeight', 'bold');
else
    suptitle('干扰对 PRN 码相关峰的影响 (Impact of Jamming on Correlation Peak)');
end


%% ============================================================
%  第 5 部分：抗干扰算法实现
%  Part 5: Anti-Jamming Algorithms
%
%  针对三种干扰类型，实现对应的抗干扰算法：
%   (a) 自适应陷波器   → 抑制窄带 CW 干扰
%   (b) 频域阈值抑制   → 抑制宽带噪声干扰
%   (c) 脉冲消隐       → 抑制脉冲干扰
% ============================================================
fprintf('▶ [5/6] 抗干扰算法实现\n');

% ══════════════════════════════════════════════════════════
%  5.1 自适应陷波器 (Adaptive Notch Filter)
%      对抗干扰类型：窄带连续波 (CW)
%
%  原理：利用 LMS 算法自适应跟踪干扰频率，生成
%        与干扰幅度相等、相位相反的信号来抵消干扰。
%  结构：2 权重 LMS 滤波器
%        参考输入：cos(ω_n) 和 sin(ω_n)（由 FFT 估计频率）
%        期望响应：接收信号
%        误差输出：抗干扰后的信号
% ══════════════════════════════════════════════════════════
fprintf('  → 5.1 自适应陷波器 (对抗窄带 CW 干扰)\n');

% 步骤1：从 FFT 估计干扰频率
X_rx_cw = fftshift(fft(rx_cw, N_fft));
X_mag = abs(X_rx_cw) / N_fft;
[~, peak_bin] = max(X_mag);
freq_est = f_axis(peak_bin);  % 估计的干扰频率
fprintf('     干扰频率估计: 真实 %.3f MHz → 估计 %.3f MHz\n', ...
        jam_freq_cw/1e6, freq_est/1e6);

% 步骤2：生成参考信号
omega = 2*pi * freq_est;
ref_cos = cos(omega * t);
ref_sin = sin(omega * t);

% 步骤3：LMS 自适应滤波
w_cos = 0; w_sin = 0;  % 权重初始值
notch_out = zeros(1, n_samples);

for n = 1:n_samples
    % 干扰估计
    jam_est = w_cos * ref_cos(n) + w_sin * ref_sin(n);
    % 误差 = 抗干扰后信号
    e = rx_cw(n) - jam_est;
    notch_out(n) = e;
    % LMS 权重更新
    w_cos = w_cos + mu_notch * e * ref_cos(n);
    w_sin = w_sin + mu_notch * e * ref_sin(n);
end

% 评估陷波效果
corr_notch = xcorr(notch_out, local_ref, 'normalized');
peak_notch = max(abs(corr_notch));
atten_notch = 20*log10(peak_notch / peak_clean);
cw_improvement = atten_notch - atten_cw;  % 改善量 (dB)

fprintf('     相关峰恢复: 干扰前 %.3f → 抗干扰后 %.3f\n', peak_cw, peak_notch);
fprintf('     改善量: %.1f dB  (从 %.1f dB 到 %.1f dB)\n\n', ...
        cw_improvement, atten_cw, atten_notch);


% ══════════════════════════════════════════════════════════
%  5.2 频域阈值抑制 (Frequency Domain Excision)
%      对抗干扰类型：宽带噪声干扰
%
%  原理：变换到频域后，将功率超过阈值的频点置零，
%        再变换回时域。宽带干扰功率分布在多个频点，
%        通过阈值检测识别并切除受污染严重的频段。
% ══════════════════════════════════════════════════════════
fprintf('  → 5.2 频域阈值抑制 (对抗宽带噪声干扰)\n');

% 步骤1：FFT 到频域
%  注意：工程实现中会用加窗+重叠保留法(Overlap-Save)来避免
%  时域失真。这里为简化演示，使用不加窗整帧 FFT + IFFT，
%  对噪声类干扰仍能有效抑制。
X_wb = fftshift(fft(rx_wb, N_fft));

% 步骤3：功率谱与阈值
power_spec = abs(X_wb).^2 / N_fft;
spec_mean = mean(power_spec);
spec_std  = std(power_spec);
threshold = spec_mean + excise_factor * spec_std;

% 步骤4：找到超阈值频点并记录
excise_mask = power_spec > threshold;
n_excised = sum(excise_mask);
fprintf('     阈值 = mean + %.1f×std = %.2e\n', excise_factor, threshold);
fprintf('     切除频点数: %d / %d (%.1f%%)\n', ...
        n_excised, N_fft, n_excised/N_fft*100);

% 步骤5：频域置零（切除干扰） 保留直流分量
X_wb_excised = X_wb;
X_wb_excised(excise_mask) = 0;

% 步骤6：IFFT 回时域
wb_excised = real(ifft(ifftshift(X_wb_excised), N_fft));
wb_excised = wb_excised(1:n_samples);

% 评估频域抑制效果
corr_wb_excised = xcorr(wb_excised, local_ref, 'normalized');
peak_wb_excised = max(abs(corr_wb_excised));
atten_wb_excised = 20*log10(peak_wb_excised / peak_clean);
wb_improvement = atten_wb_excised - atten_wb;

fprintf('     相关峰恢复: 干扰前 %.3f → 抗干扰后 %.3f\n', peak_wb, peak_wb_excised);
fprintf('     改善量: %.1f dB  (从 %.1f dB 到 %.1f dB)\n\n', ...
        wb_improvement, atten_wb, atten_wb_excised);


% ══════════════════════════════════════════════════════════
%  5.3 脉冲消隐 (Pulse Blanking)
%      对抗干扰类型：脉冲干扰
%
%  原理：检测信号中的高功率脉冲，将受污染时段的
%        采样值置零（消隐），保留无脉冲时段的有效信号。
%        常用方法：短时能量检测 + 自适应阈值。
% ══════════════════════════════════════════════════════════
fprintf('  → 5.3 脉冲消隐 (对抗脉冲干扰)\n');

% 步骤1：计算短时能量（滑动窗口）
window_len = round(Fs * 2e-6);  % 2μs 窗（亚码片尺度）
energy = conv(rx_pulse.^2, ones(1, window_len)/window_len, 'same');

% 步骤2：用中值 + MAD 设定稳健阈值（抗异常值）
energy_median = median(energy);
energy_mad = median(abs(energy - energy_median));
blank_threshold = energy_median + blank_factor * energy_mad * 1.4826;
   % 1.4826 使 MAD 逼近高斯分布的标准差

% 步骤3：生成消隐掩码
blank_mask = energy > blank_threshold;
n_blanked = sum(blank_mask);
fprintf('     阈值 (中值 + %.1f×MAD) = %.2e\n', blank_factor, blank_threshold);
fprintf('     消隐采样点: %d / %d (%.1f%%)\n', ...
        n_blanked, n_samples, n_blanked/n_samples*100);

% 步骤4：应用平滑过渡避免瞬态
smooth_kernel = ones(1, smooth_win) / smooth_win;
blank_mask_smooth = conv(double(blank_mask), smooth_kernel, 'same') > 0.5;

% 步骤5：脉冲消隐
pulse_blanked = rx_pulse;
pulse_blanked(blank_mask_smooth) = 0;

% 评估脉冲消隐效果
corr_blanked = xcorr(pulse_blanked, local_ref, 'normalized');
peak_blanked = max(abs(corr_blanked));
atten_blanked = 20*log10(peak_blanked / peak_clean);
pulse_improvement = atten_blanked - atten_pulse;

fprintf('     相关峰恢复: 干扰前 %.3f → 抗干扰后 %.3f\n', peak_pulse, peak_blanked);
fprintf('     改善量: %.1f dB  (从 %.1f dB 到 %.1f dB)\n\n', ...
        pulse_improvement, atten_pulse, atten_blanked);


% ── 图 4：三种抗干扰算法效果对比 ──
figure('Name', '抗干扰算法效果', 'Position', [100, 100, 1400, 800]);

% 第1行：时域波形对比（只取部分点）
n_plot = 1500;  % 显示点数
t_plot = t(1:n_plot) * 1e6;

% --- 自适应陷波器 ---
subplot(3,3,1);
plot(t_plot, rx_cw(1:n_plot), 'r-', 'LineWidth', 0.6);
title(sprintf('窄带干扰 (CW) 时域 (JSR=%ddB)', JSR_CW_dB));
ylabel('幅度'); grid on;
xlim([0, max(t_plot)]);

subplot(3,3,2);
plot(t_plot, notch_out(1:n_plot), 'b-', 'LineWidth', 0.8);
title(sprintf('陷波器输出  |  改善 %.1f dB', cw_improvement));
ylabel('幅度'); grid on;
xlim([0, max(t_plot)]);

subplot(3,3,3);
plot(lags_us, abs(corr_cw), 'r--', 'LineWidth', 1.0); hold on;
plot(lags_us, abs(corr_notch), 'b-', 'LineWidth', 1.5);
legend('干扰后', '陷波后', 'Location', 'northeast');
title('相关峰恢复对比');
xlabel('时延 (μs)'); ylabel('归一化相关');
xlim([-20, 20]); grid on;

% --- 频域抑制 ---
subplot(3,3,4);
plot(t_plot, rx_wb(1:n_plot), 'r-', 'LineWidth', 0.6);
title(sprintf('宽带干扰 时域 (JSR=%ddB)', JSR_WB_dB));
ylabel('幅度'); grid on;
xlim([0, max(t_plot)]);

subplot(3,3,5);
plot(t_plot, wb_excised(1:n_plot), 'b-', 'LineWidth', 0.8);
title(sprintf('频域抑制输出  |  改善 %.1f dB', wb_improvement));
ylabel('幅度'); grid on;
xlim([0, max(t_plot)]);

% 频域抑制前后频谱对比
subplot(3,3,6);
X_after_wb = fftshift(fft(wb_excised, N_fft));
plot(f_axis/1e6, abs(X_wb)/N_fft, 'r--', 'LineWidth', 0.8); hold on;
plot(f_axis/1e6, abs(X_after_wb)/N_fft, 'b-', 'LineWidth', 1.0);
legend('抑制前', '抑制后', 'Location', 'northeast');
title('频域抑制 前后频谱');
xlabel('频率 (MHz)'); ylabel('幅度');
xlim([-2, 10]); grid on;

% --- 脉冲消隐 ---
subplot(3,3,7);
plot(t_plot, rx_pulse(1:n_plot), 'r-', 'LineWidth', 0.6);
title(sprintf('脉冲干扰 时域 (JSR=%ddB)', JSR_Pulse_dB));
ylabel('幅度'); grid on;
xlim([0, max(t_plot)]);

subplot(3,3,8);
plot(t_plot, pulse_blanked(1:n_plot), 'b-', 'LineWidth', 0.8);
title(sprintf('脉冲消隐输出  |  改善 %.1f dB', pulse_improvement));
ylabel('幅度'); grid on;
xlim([0, max(t_plot)]);

% 消隐掩码展示
subplot(3,3,9);
plot(lags_us, abs(corr_pulse), 'r--', 'LineWidth', 1.0); hold on;
plot(lags_us, abs(corr_blanked), 'b-', 'LineWidth', 1.5);
legend('干扰后', '消隐后', 'Location', 'northeast');
title('相关峰恢复对比');
xlabel('时延 (μs)'); ylabel('归一化相关');
xlim([-20, 20]); grid on;

if ~verLessThan('matlab', '9.4')
    sgtitle('三种抗干扰算法效果对比 (Anti-Jamming Algorithm Comparison)', ...
            'FontSize', 13, 'FontWeight', 'bold');
else
    suptitle('三种抗干扰算法效果对比 (Anti-Jamming Algorithm Comparison)');
end


%% ============================================================
%  第 6 部分：性能评估与总结
%  Part 6: Performance Evaluation and Summary
%
%  综合对比三种干扰 × 三种算法的效果
%  生成性能表格和总结报告
% ============================================================
fprintf('▶ [6/6] 性能评估报告\n\n');

% ── 6.1 综合性能表格 ──
fprintf('┌─────────────────────────────────────────────────────────────┐\n');
fprintf('│              北斗 B1I 抗干扰性能评估报告                      │\n');
fprintf('│          Beidou B1I Anti-Jamming Performance Report         │\n');
fprintf('├──────────────────────┬──────────┬──────────┬────────────────┤\n');
fprintf('│      场景            │ 相关峰    │ 衰减(dB)  │ 改善量(dB)    │\n');
fprintf('├──────────────────────┼──────────┼──────────┼────────────────┤\n');
fprintf('│ ① 干净信号 (基准)    │ %.4f  │  0.0      │    —          │\n', peak_clean);
fprintf('│ ② + CW 窄带干扰      │ %.4f  │ %+.1f     │    —          │\n', peak_cw, atten_cw);
fprintf('│    → 自适应陷波器后   │ %.4f  │ %+.1f     │  %+.1f        │\n', peak_notch, atten_notch, cw_improvement);
fprintf('│ ③ + 宽带噪声干扰     │ %.4f  │ %+.1f     │    —          │\n', peak_wb, atten_wb);
fprintf('│    → 频域阈值抑制后   │ %.4f  │ %+.1f     │  %+.1f        │\n', peak_wb_excised, atten_wb_excised, wb_improvement);
fprintf('│ ④ + 脉冲干扰         │ %.4f  │ %+.1f     │    —          │\n', peak_pulse, atten_pulse);
fprintf('│    → 脉冲消隐后       │ %.4f  │ %+.1f     │  %+.1f        │\n', peak_blanked, atten_blanked, pulse_improvement);
fprintf('└──────────────────────┴──────────┴──────────┴────────────────┘\n\n');

% ── 6.2 结论与总结 ──
fprintf('═══ 总结与结论 ═══\n');
fprintf('  1. 北斗 B1I 信号结构\n');
fprintf('     - 载波: 1561.098 MHz (仿真中频 %.3f MHz)\n', IF/1e6);
fprintf('     - 码速率: %.3f Mcps | 码长: %d chips\n', code_rate/1e6, code_len);
fprintf('     - 调制方式: BPSK (导频)/QPSK (数据)\n\n');

fprintf('  2. 三种干扰对相关峰的影响\n');
if abs(atten_cw) > 10
    fprintf('     ⚠ CW 干扰造成相关峰严重衰减 (%.1f dB)，捕获困难\n', atten_cw);
else
    fprintf('     ✓ CW 干扰影响可控 (%.1f dB)\n', atten_cw);
end
if abs(atten_wb) > 10
    fprintf('     ⚠ 宽带干扰造成相关峰严重衰减 (%.1f dB)，捕获困难\n', atten_wb);
else
    fprintf('     ✓ 宽带干扰影响可控 (%.1f dB)\n', atten_wb);
end
if abs(atten_pulse) > 10
    fprintf('     ⚠ 脉冲干扰造成相关峰严重衰减 (%.1f dB)，捕获困难\n', atten_pulse);
else
    fprintf('     ✓ 脉冲干扰影响可控 (%.1f dB)\n', atten_pulse);
end
fprintf('\n');

fprintf('  3. 抗干扰算法效果\n');
if cw_improvement > 0
    fprintf('     ✓ 自适应陷波器: 改善 %.1f dB', cw_improvement);
    if cw_improvement > 10
        fprintf('  ★ 效果显著\n');
    else
        fprintf('\n');
    end
else
    fprintf('     △ 自适应陷波器: 效果有限 (%.1f dB)\n', cw_improvement);
end

if wb_improvement > 0
    fprintf('     ✓ 频域阈值抑制: 改善 %.1f dB', wb_improvement);
    if wb_improvement > 10
        fprintf('  ★ 效果显著\n');
    else
        fprintf('\n');
    end
else
    fprintf('     △ 频域阈值抑制: 效果有限 (%.1f dB)\n', wb_improvement);
end

if pulse_improvement > 0
    fprintf('     ✓ 脉冲消隐:     改善 %.1f dB', pulse_improvement);
    if pulse_improvement > 10
        fprintf('  ★ 效果显著\n');
    else
        fprintf('\n');
    end
else
    fprintf('     △ 脉冲消隐: 效果有限 (%.1f dB)\n', pulse_improvement);
end
fprintf('\n');

fprintf('  4. 可扩展方向\n');
fprintf('     - 空域抗干扰: 阵列天线 + 零陷形成 (Spatial Nulling)\n');
fprintf('     - 空时自适应处理: STAP (Space-Time Adaptive Processing)\n');
fprintf('     - 频域重叠变换: FDOA (Frequency Domain Overlap-Add)\n');
fprintf('     - 深度学习抗干扰: CNN/LSTM 检测与抑制\n');
fprintf('     - 多星座联合: GPS L1 + BDS B1 + Galileo E1\n\n');

fprintf('╔══════════════════════════════════════════════╗\n');
fprintf('║  仿真完成！感谢使用北斗抗干扰仿真系统        ║\n');
fprintf('║  Simulation Complete. Happy Navigating!     ║\n');
fprintf('╚══════════════════════════════════════════════╝\n');
